### ISSUE TITLE
Sample - UI - GameMenu.sln

### ISSUE THREAD

**Issue by dud3** [SiliconStudio/xenko-samples#2]
Requires `MS-Mincho`: http://www.ffonts.net/MS-Mincho.font.download

If we could document this would be great. =)

Thanks.

**Comment by xenux** [comment]
Hi dud,

Is this font missing on your system? (It supposed to be included by default on most windows systems: https://www.microsoft.com/typography/fonts/font.aspx?FMID=206).
In that case, could you specify which version of Windows you are using?

Thank you.

**Comment by dud3** [comment]
I happen to have `Windows 10 - home` which I upgraded from `Windows 8` following their official site instructions.

At the bottom of the page there seem to be a table titled: `Products that supply this font`, now that I saw it, `windows 10` seems not to be there, ;( or did I miss anything?

Thanks. =)

**Comment by xenux** [comment]
We fixed the problem by replacing MS Mincho by a free font that we embed in the sample.
The should be resolved in next release. Thanks again for the report.

**Comment by dud3** [comment]
Thanks.
