### ISSUE TITLE
Sample - Graphics - Simple Terrain

### ISSUE THREAD

**Issue by dud3** [SiliconStudio/xenko-samples#3]
Hi Guys,

It seem to not work.

I'm not sure if this one is already fixed, since I'm still running on 1.5.2-beta. =)

Thanks.

## Debug logs
![xenko-001](https://cloud.githubusercontent.com/assets/5823644/14061947/7745f728-f38e-11e5-81e5-6d32aff42fe5.png)
![xenko-002](https://cloud.githubusercontent.com/assets/5823644/14061948/77460eac-f38e-11e5-9da5-4c3bb066ab9d.png)

http://pastebin.com/gLSc64yq
http://pastebin.com/UMVd9unY
http://pastebin.com/KpwkPPPE

**Comment by jwollen** [comment]
Thanks for the report!

Could you provide some more details? Do have any build errors or exceptions at runtime?

**Comment by dud3** [comment]
Hi @jwollen, Sorry for my late reply.

I just update the first comment: https://github.com/SiliconStudio/xenko-samples/issues/3#issue-142443590

**Comment by dud3** [comment]
Upgrading it to 1.6.2-beta solved it.
